application: word-fun
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: web/static

- url: /
  script: web.pages.index.app
  
- url: /api/(.*)
  script: api.\1.app

- url: /scoreboard[\/]?(.*)
  script: web.pages.scoreboard.app

- url: /game
  script: web.pages.game.app
  
- url: /connect
  script: web.pages.connect.app
  
#cacthes everything that wasn't cought until now
- url: /(.*)
  script: web.pages.four_o_four.app
  


libraries:
- name: webapp2
  version: "2.5.2"
